from prefetch_modeler.storage_type import fast_local1, slow_cloud1
from prefetch_modeler.core import Duration, Rate, Simulation
from prefetch_modeler.plot import io_data, wait_data, rate_data, pid_data
import matplotlib.pyplot as plt

class Member:
    def __init__(self, storage, workload, prefetcher):
        self.data = None
        self.tracer_data = None
        self._wait_view = None
        self._io_view = None
        self._rate_view = None
        self._pid_view = None
        self.storage = storage
        self.workload = workload
        self.prefetcher = prefetcher
        self.schema = None

    def run(self):
        simulation = Simulation(*self.prefetcher, *self.storage, *self.workload)

        @simulation.metric('proportional_term')
        def metric(self):
            return float(self['remaining'].proportional_term)

        @simulation.metric('proportional_term_w_coefficient')
        def metric(self):
            prefetcher = self['remaining']
            return float(prefetcher.proportional_term * prefetcher.kp)

        @simulation.metric('cnc_integral_term')
        def metric(self):
            return float(self['remaining'].cnc_integral_term)

        @simulation.metric('cnc_integral_term_w_coefficient')
        def metric(self):
            prefetcher = self['remaining']
            return float(prefetcher.cnc_integral_term * prefetcher.ki_cnc)

        @simulation.metric('awd_integral_term')
        def metric(self):
            return float(self['remaining'].awd_integral_term)

        @simulation.metric('awd_integral_term_w_coefficient')
        def metric(self):
            prefetcher = self['remaining']
            return float(prefetcher.awd_integral_term * prefetcher.ki_awd)

        @simulation.metric('demand_rate')
        def metric(self):
            return float(self['remaining'].demand_rate)

        @simulation.metric('awaiting_dispatch')
        def metric(self):
            return self['remaining'].awaiting_dispatch

        @simulation.metric('cnc_headroom')
        def metric(self):
            return self['remaining'].cnc_headroom

        @simulation.metric('wait_consume')
        def metric(self):
            completed = self['completed']
            return completed.tick_data['want_to_move'] > completed.tick_data['to_move']

        @simulation.metric('remaining_ios')
        def metric(self):
            return len(self['remaining'])

        @simulation.metric('max_iops')
        def metric(self):
            return float(self['submitted'].storage_speed)

        @simulation.metric('consumption_rate')
        def metric(self):
            return float(self['completed'].rate())

        @simulation.metric('prefetch_rate')
        def metric(self):
            return float(self['remaining'].rate())

        self.schema = simulation.schema

        result = simulation.run(1000, duration=Duration(seconds=0.2), traced=[1, 5, 100])
        data = result.bucket_data
        self.data = data.reindex(data.index.union(data.index[1:] - 1), method='ffill')
        self.tracer_data = result.tracer_data
        self.metric_data = result.metric_data

    @property
    def wait_view(self):
        if self._wait_view is None:
            self._wait_view = wait_data(self.data)
        return self._wait_view

    @property
    def rate_view(self):
        if self._rate_view is None:
            self._rate_view = rate_data(self.data)
        return self._rate_view

    @property
    def pid_view(self):
        if self._pid_view is None:
            self._pid_view = pid_data(self.data)
        return self._pid_view

    @property
    def io_view(self):
        if self._io_view is None:
            self._io_view = io_data(self.data)
        return self._io_view

    @property
    def tracer_view(self):
        return self.tracer_data


class Cohort:
    """
    DataFrames generated by running a list of prefetch algorithms and baseline
    fetchers for a given workload and storage type
    """
    def __init__(self):
        self.members = []

    def run(self, storage, workload, prefetchers):
        for prefetcher in prefetchers:
            self.members.append(Member(storage, workload, prefetcher))

        for member in self.members:
            member.run()
